name: Seat Monitor

on:
  schedule:
    - cron: "*/2 * * * *" # run every 2 minutes
  workflow_dispatch: # allows manual trigger

jobs:
  check-seats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Setup Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Install dependencies
      - run: npm install axios dotenv

      # Run monitor script
      - run: node monitor.js
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          ROLL: ${{ secrets.ROLL }}
          REG: ${{ secrets.REG }}
