name: Seat Monitor

on:
  schedule:
    - cron: "*/2 * * * *" # run every 5 minutes
  workflow_dispatch: # allows manual trigger

jobs:
  check-seats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Install Bun
      - name: Setup Bun
        run: curl -fsSL https://bun.sh/install | bash

      # Add Bun to PATH
      - name: Add Bun to PATH
        run: echo "$HOME/.bun/bin" >> $GITHUB_PATH

      # Install dependencies
      - run: bun install axios dotenv

      # Run monitor script
      - run: bun run monitor.js
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          ROLL: ${{ secrets.ROLL }}
          REG: ${{ secrets.REG }}
